export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8

export ZSHRC_DIR=${${(%):-%N}:A:h}

export BAT_THEME="OneHalfDark"
export KEYTIMEOUT=5
export EDITOR=nvim

path+=(
  ~/.bin
  ~/bin
  ~/.local/bin
  $GOPATH/bin
)


export __ENABLE_TMUX=
