export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8

export BAT_THEME="OneHalfDark"
export KEYTIMEOUT=5
export EDITOR=nvim

path=(
  ~/.bin
  ~/bin
  ~/.local/bin
  $GOPATH/bin
  $path
)

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done


export __ENABLE_TMUX=
