return {
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  files = {
    modified = "",
    readonly = "",
  },
  separator = { left = "", right = "" },
  separator_tab = { left = "", right = "" },
  other = {
    command = " ",
    search = " ",
    exit = "󰗼 ",
    close = " ",
  },
  git = {
    added = "",
    removed = "",
    merged = "",
    branch = "",
    ignored = "",
    staged = "",
    renamed = "󰑕",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = "󰉋 ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  mode = {
    n = "",
    i = "",
    v = "󰦨",
    V = "",
    ["^V"] = "󰿦",
    c = "",
    s = "",
    R = "󰉼",
    r = "",
    ["?"] = "",
    ["!"] = "󰜎",
    t = "",
    o = "∙",
  },
}
