local opts = { silent = true }
local keymap = vim.keymap
keymap.set('n', '<F5>', function() require('dap').continue() end, opts)
keymap.set('n', '<F10>', function() require('dap').step_over() end, opts)
keymap.set('n', '<F11>', function () require('dap').step_into() end, opts)
keymap.set('n', '<F12>', function () require('dap').step_out() end, opts)
keymap.set('n', '<Leader>db', function () require('dap').toggle_breakpoint() end, opts)
keymap.set('n', '<Leader>dB', function () require('dap').set_breakpoint() end, opts)
keymap.set('n', '<Leader>dlp', function () require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end, opts)
keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end, opts)
keymap.set('n', '<Leader>dl', function() require('dap').run_last() end, opts)
keymap.set('n', '<Leader>dd', function() require('dapui').toggle() end, opts)
keymap.set({'n', 'v'}, '<Leader>dh', function()
      require('dap.ui.widgets').hover()
    end, opts)
    keymap.set({'n', 'v'}, '<Leader>dp', function()
      require('dap.ui.widgets').preview()
    end, opts)
    keymap.set('n', '<Leader>df', function()
      local widgets = require('dap.ui.widgets')
      widgets.centered_float(widgets.frames)
    end, opts)
    keymap.set('n', '<Leader>ds', function()
      local widgets = require('dap.ui.widgets')
      widgets.centered_float(widgets.scopes)
    end, opts)

