lastupdatecheck: 0
recentrepos:
- /home/natai/src/github.com/natainakata/fcc-js-algorithms-and-data-structures
startuppopupversion: 5
lastversion: 0.41.0
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
