modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      # Space:
      #   held: SUPER_L
      # alone: Space
  # - name: Shift IME
  #   application:
  #     not: /Minecraft*/
  #   remap:
  #     Shift_R:
  #       held: Shift_R
  #       alone: KEY_HENKAN
  #     Shift_L:
  #       held: Shift_L
  #       alone: KEY_MUHENKAN
