name: Install Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install zsh
        run: sudo apt install zsh

      - name: Run Install Test
        run: curl -fsSL https://github.com/natainakata/dotfiles/raw/main/installer.sh | bash
      - name: Check Install
        run: |
          zsh -i -c exit
          hyperfine -w 5 -r 50 'zsh -i -c exit'
